# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fit-programm.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 896)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Fit_tab = QtWidgets.QWidget()
        self.Fit_tab.setObjectName("Fit_tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.Fit_tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Button_dropped_points = QtWidgets.QPushButton(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Button_dropped_points.setFont(font)
        self.Button_dropped_points.setObjectName("Button_dropped_points")
        self.gridLayout.addWidget(self.Button_dropped_points, 2, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.Scroll_Bar_dropped_points = QtWidgets.QScrollBar(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Scroll_Bar_dropped_points.setFont(font)
        self.Scroll_Bar_dropped_points.setOrientation(QtCore.Qt.Horizontal)
        self.Scroll_Bar_dropped_points.setObjectName("Scroll_Bar_dropped_points")
        self.gridLayout.addWidget(self.Scroll_Bar_dropped_points, 2, 2, 1, 1)
        self.comboBox_Fit_num = QtWidgets.QComboBox(self.Fit_tab)
        self.comboBox_Fit_num.setMaximumSize(QtCore.QSize(101, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_Fit_num.setFont(font)
        self.comboBox_Fit_num.setObjectName("comboBox_Fit_num")
        self.comboBox_Fit_num.addItem("")
        self.comboBox_Fit_num.addItem("")
        self.comboBox_Fit_num.addItem("")
        self.comboBox_Fit_num.addItem("")
        self.gridLayout.addWidget(self.comboBox_Fit_num, 1, 1, 1, 1)
        self.comboBox_fit_model = QtWidgets.QComboBox(self.Fit_tab)
        self.comboBox_fit_model.setMaximumSize(QtCore.QSize(197, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_fit_model.setFont(font)
        self.comboBox_fit_model.setObjectName("comboBox_fit_model")
        self.comboBox_fit_model.addItem("")
        self.comboBox_fit_model.addItem("")
        self.comboBox_fit_model.addItem("")
        self.comboBox_fit_model.addItem("")
        self.comboBox_fit_model.addItem("")
        self.gridLayout.addWidget(self.comboBox_fit_model, 1, 0, 1, 1)
        self.Dropped_points_edit = QtWidgets.QLineEdit(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Dropped_points_edit.setFont(font)
        self.Dropped_points_edit.setObjectName("Dropped_points_edit")
        self.gridLayout.addWidget(self.Dropped_points_edit, 3, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 1, 1, 1)
        self.select_datanumber = QtWidgets.QSpinBox(self.Fit_tab)
        self.select_datanumber.setObjectName("select_datanumber")
        self.gridLayout.addWidget(self.select_datanumber, 1, 2, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.constraints = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.constraints.setFont(font)
        self.constraints.setObjectName("constraints")
        self.verticalLayout_3.addWidget(self.constraints)
        self.init_alphatext_2 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_alphatext_2.setFont(font)
        self.init_alphatext_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.init_alphatext_2.setObjectName("init_alphatext_2")
        self.verticalLayout_3.addWidget(self.init_alphatext_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.alpha_con_min = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.alpha_con_min.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.alpha_con_min.setDecimals(4)
        self.alpha_con_min.setMinimum(0.0)
        self.alpha_con_min.setSingleStep(1000.0)
        self.alpha_con_min.setObjectName("alpha_con_min")
        self.horizontalLayout.addWidget(self.alpha_con_min)
        self.label_8 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.alpha_con_max = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.alpha_con_max.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.alpha_con_max.setDecimals(4)
        self.alpha_con_max.setMaximum(1.0)
        self.alpha_con_max.setSingleStep(0.01)
        self.alpha_con_max.setProperty("value", 1.0)
        self.alpha_con_max.setObjectName("alpha_con_max")
        self.horizontalLayout.addWidget(self.alpha_con_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.init_Rtext_2 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Rtext_2.setFont(font)
        self.init_Rtext_2.setObjectName("init_Rtext_2")
        self.verticalLayout_3.addWidget(self.init_Rtext_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.R_con_min = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.R_con_min.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.R_con_min.setDecimals(4)
        self.R_con_min.setSingleStep(0.01)
        self.R_con_min.setObjectName("R_con_min")
        self.horizontalLayout_2.addWidget(self.R_con_min)
        self.label_11 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.R_con_max = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.R_con_max.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.R_con_max.setDecimals(4)
        self.R_con_max.setSingleStep(0.001)
        self.R_con_max.setProperty("value", 0.15)
        self.R_con_max.setObjectName("R_con_max")
        self.horizontalLayout_2.addWidget(self.R_con_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.init_dBtext_2 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_dBtext_2.setFont(font)
        self.init_dBtext_2.setObjectName("init_dBtext_2")
        self.verticalLayout_3.addWidget(self.init_dBtext_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.dB_con_min = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.dB_con_min.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.dB_con_min.setDecimals(4)
        self.dB_con_min.setSingleStep(0.0001)
        self.dB_con_min.setProperty("value", 0.0001)
        self.dB_con_min.setObjectName("dB_con_min")
        self.horizontalLayout_3.addWidget(self.dB_con_min)
        self.label_13 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.dB_con_max = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.dB_con_max.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.dB_con_max.setDecimals(4)
        self.dB_con_max.setSingleStep(0.01)
        self.dB_con_max.setProperty("value", 0.5)
        self.dB_con_max.setObjectName("dB_con_max")
        self.horizontalLayout_3.addWidget(self.dB_con_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.init_Atext_2 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Atext_2.setFont(font)
        self.init_Atext_2.setObjectName("init_Atext_2")
        self.verticalLayout_3.addWidget(self.init_Atext_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.A_con_min = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.A_con_min.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.A_con_min.setDecimals(4)
        self.A_con_min.setObjectName("A_con_min")
        self.horizontalLayout_4.addWidget(self.A_con_min)
        self.label_15 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.A_con_max = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.A_con_max.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.A_con_max.setDecimals(4)
        self.A_con_max.setProperty("value", 15.0)
        self.A_con_max.setObjectName("A_con_max")
        self.horizontalLayout_4.addWidget(self.A_con_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.init_Rtext_3 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Rtext_3.setFont(font)
        self.init_Rtext_3.setObjectName("init_Rtext_3")
        self.verticalLayout_3.addWidget(self.init_Rtext_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.slope_con_min = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.slope_con_min.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.slope_con_min.setDecimals(4)
        self.slope_con_min.setMinimum(-50.0)
        self.slope_con_min.setMaximum(50.0)
        self.slope_con_min.setSingleStep(0.5)
        self.slope_con_min.setProperty("value", -5.0)
        self.slope_con_min.setObjectName("slope_con_min")
        self.horizontalLayout_5.addWidget(self.slope_con_min)
        self.label_17 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.slope_con_max = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.slope_con_max.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.slope_con_max.setDecimals(4)
        self.slope_con_max.setMinimum(-50.0)
        self.slope_con_max.setMaximum(50.0)
        self.slope_con_max.setSingleStep(0.5)
        self.slope_con_max.setProperty("value", 5.0)
        self.slope_con_max.setObjectName("slope_con_max")
        self.horizontalLayout_5.addWidget(self.slope_con_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.init_Rtext_4 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Rtext_4.setFont(font)
        self.init_Rtext_4.setObjectName("init_Rtext_4")
        self.verticalLayout_3.addWidget(self.init_Rtext_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.offset_con_min = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.offset_con_min.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.offset_con_min.setDecimals(4)
        self.offset_con_min.setMinimum(-50.0)
        self.offset_con_min.setMaximum(50.0)
        self.offset_con_min.setSingleStep(0.5)
        self.offset_con_min.setProperty("value", -5.0)
        self.offset_con_min.setObjectName("offset_con_min")
        self.horizontalLayout_6.addWidget(self.offset_con_min)
        self.label_19 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.offset_con_max = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.offset_con_max.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.offset_con_max.setDecimals(4)
        self.offset_con_max.setMinimum(-50.0)
        self.offset_con_max.setMaximum(50.0)
        self.offset_con_max.setSingleStep(0.5)
        self.offset_con_max.setProperty("value", 5.0)
        self.offset_con_max.setObjectName("offset_con_max")
        self.horizontalLayout_6.addWidget(self.offset_con_max)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.init_offsettext = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_offsettext.setFont(font)
        self.init_offsettext.setObjectName("init_offsettext")
        self.gridLayout_3.addWidget(self.init_offsettext, 5, 4, 1, 1)
        self.init_Atext = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Atext.setFont(font)
        self.init_Atext.setObjectName("init_Atext")
        self.gridLayout_3.addWidget(self.init_Atext, 5, 2, 1, 1)
        self.init_Slopetext = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Slopetext.setFont(font)
        self.init_Slopetext.setObjectName("init_Slopetext")
        self.gridLayout_3.addWidget(self.init_Slopetext, 3, 4, 1, 1)
        self.init_alphatext = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_alphatext.setFont(font)
        self.init_alphatext.setObjectName("init_alphatext")
        self.gridLayout_3.addWidget(self.init_alphatext, 3, 0, 1, 1)
        self.init_dBtext = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_dBtext.setFont(font)
        self.init_dBtext.setObjectName("init_dBtext")
        self.gridLayout_3.addWidget(self.init_dBtext, 5, 0, 1, 1)
        self.init_Rtext = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_Rtext.setFont(font)
        self.init_Rtext.setObjectName("init_Rtext")
        self.gridLayout_3.addWidget(self.init_Rtext, 3, 2, 1, 1)
        self.init_alpha = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.init_alpha.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.init_alpha.setDecimals(4)
        self.init_alpha.setMaximum(1.0)
        self.init_alpha.setSingleStep(0.01)
        self.init_alpha.setProperty("value", 0.0001)
        self.init_alpha.setObjectName("init_alpha")
        self.gridLayout_3.addWidget(self.init_alpha, 4, 0, 1, 1)
        self.init_dB = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.init_dB.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.init_dB.setDecimals(4)
        self.init_dB.setMaximum(100.0)
        self.init_dB.setSingleStep(0.001)
        self.init_dB.setProperty("value", 0.03)
        self.init_dB.setObjectName("init_dB")
        self.gridLayout_3.addWidget(self.init_dB, 6, 0, 1, 1)
        self.init_R = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.init_R.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.init_R.setDecimals(4)
        self.init_R.setSingleStep(0.001)
        self.init_R.setProperty("value", 0.08)
        self.init_R.setObjectName("init_R")
        self.gridLayout_3.addWidget(self.init_R, 4, 2, 1, 1)
        self.init_A = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.init_A.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.init_A.setDecimals(4)
        self.init_A.setMaximum(10000.0)
        self.init_A.setSingleStep(0.5)
        self.init_A.setProperty("value", 7.0)
        self.init_A.setObjectName("init_A")
        self.gridLayout_3.addWidget(self.init_A, 6, 2, 1, 1)
        self.init_slope = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.init_slope.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.init_slope.setDecimals(4)
        self.init_slope.setMinimum(-50.0)
        self.init_slope.setMaximum(50.0)
        self.init_slope.setSingleStep(0.5)
        self.init_slope.setProperty("value", 0.5)
        self.init_slope.setObjectName("init_slope")
        self.gridLayout_3.addWidget(self.init_slope, 4, 4, 1, 1)
        self.init_offset = QtWidgets.QDoubleSpinBox(self.Fit_tab)
        self.init_offset.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.init_offset.setDecimals(4)
        self.init_offset.setMinimum(-50.0)
        self.init_offset.setMaximum(50.0)
        self.init_offset.setSingleStep(0.5)
        self.init_offset.setProperty("value", 3.0)
        self.init_offset.setObjectName("init_offset")
        self.gridLayout_3.addWidget(self.init_offset, 6, 4, 1, 1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_3)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Button_Plot = QtWidgets.QPushButton(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Button_Plot.setFont(font)
        self.Button_Plot.setObjectName("Button_Plot")
        self.gridLayout_7.addWidget(self.Button_Plot, 0, 0, 1, 1)
        self.Button_set_fit_params = QtWidgets.QPushButton(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Button_set_fit_params.setFont(font)
        self.Button_set_fit_params.setObjectName("Button_set_fit_params")
        self.gridLayout_7.addWidget(self.Button_set_fit_params, 1, 0, 1, 1)
        self.label_show_load = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_show_load.setFont(font)
        self.label_show_load.setFrameShape(QtWidgets.QFrame.Box)
        self.label_show_load.setText("")
        self.label_show_load.setObjectName("label_show_load")
        self.gridLayout_7.addWidget(self.label_show_load, 1, 1, 1, 1)
        self.label_show_init_params = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_show_init_params.setFont(font)
        self.label_show_init_params.setFrameShape(QtWidgets.QFrame.Box)
        self.label_show_init_params.setText("")
        self.label_show_init_params.setObjectName("label_show_init_params")
        self.gridLayout_7.addWidget(self.label_show_init_params, 0, 1, 1, 1)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_7)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Button_dyn_fit = QtWidgets.QPushButton(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Button_dyn_fit.setFont(font)
        self.Button_dyn_fit.setObjectName("Button_dyn_fit")
        self.gridLayout_5.addWidget(self.Button_dyn_fit, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_5.addWidget(self.progressBar, 0, 1, 1, 1)
        self.checkBox_dynPlot = QtWidgets.QCheckBox(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_dynPlot.setFont(font)
        self.checkBox_dynPlot.setObjectName("checkBox_dynPlot")
        self.gridLayout_5.addWidget(self.checkBox_dynPlot, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 2, 1, 1)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_5)
        self.horizontalLayout_7.addLayout(self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.min_drop_Bar = QtWidgets.QScrollBar(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.min_drop_Bar.setFont(font)
        self.min_drop_Bar.setOrientation(QtCore.Qt.Vertical)
        self.min_drop_Bar.setObjectName("min_drop_Bar")
        self.gridLayout_11.addWidget(self.min_drop_Bar, 0, 0, 1, 1)
        self.min_drop_value = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.min_drop_value.setFont(font)
        self.min_drop_value.setAlignment(QtCore.Qt.AlignCenter)
        self.min_drop_value.setObjectName("min_drop_value")
        self.gridLayout_11.addWidget(self.min_drop_value, 1, 0, 1, 1)
        self.Drop_label = QtWidgets.QLabel(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Drop_label.setFont(font)
        self.Drop_label.setObjectName("Drop_label")
        self.gridLayout_11.addWidget(self.Drop_label, 1, 2, 1, 1)
        self.Drop_Scalebar = QtWidgets.QScrollBar(self.Fit_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Drop_Scalebar.setFont(font)
        self.Drop_Scalebar.setMaximum(1023)
        self.Drop_Scalebar.setOrientation(QtCore.Qt.Horizontal)
        self.Drop_Scalebar.setObjectName("Drop_Scalebar")
        self.gridLayout_11.addWidget(self.Drop_Scalebar, 1, 1, 1, 1)
        self.plotView = PlotWidget(self.Fit_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotView.sizePolicy().hasHeightForWidth())
        self.plotView.setSizePolicy(sizePolicy)
        self.plotView.setMinimumSize(QtCore.QSize(750, 250))
        self.plotView.setMaximumSize(QtCore.QSize(1500, 500))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plotView.setFont(font)
        self.plotView.setObjectName("plotView")
        self.gridLayout_11.addWidget(self.plotView, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.label_params_output = QtWidgets.QLabel(self.Fit_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_params_output.sizePolicy().hasHeightForWidth())
        self.label_params_output.setSizePolicy(sizePolicy)
        self.label_params_output.setMinimumSize(QtCore.QSize(399, 539))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_params_output.setFont(font)
        self.label_params_output.setAutoFillBackground(False)
        self.label_params_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_params_output.setText("")
        self.label_params_output.setObjectName("label_params_output")
        self.verticalLayout_2.addWidget(self.label_params_output)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout_14.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.tabWidget.addTab(self.Fit_tab, "")
        self.colour_tab = QtWidgets.QWidget()
        self.colour_tab.setObjectName("colour_tab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.colour_tab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_24 = QtWidgets.QLabel(self.colour_tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_24)
        self.label_5 = QtWidgets.QLabel(self.colour_tab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.colour_button = QtWidgets.QPushButton(self.colour_tab)
        self.colour_button.setObjectName("colour_button")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.colour_button)
        self.label_21 = QtWidgets.QLabel(self.colour_tab)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.colour_tick_edit = QtWidgets.QLineEdit(self.colour_tab)
        self.colour_tick_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.colour_tick_edit.setObjectName("colour_tick_edit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.colour_tick_edit)
        self.label_22 = QtWidgets.QLabel(self.colour_tab)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.colour_map_edit = QtWidgets.QLineEdit(self.colour_tab)
        self.colour_map_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.colour_map_edit.setObjectName("colour_map_edit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.colour_map_edit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.label_25 = QtWidgets.QLabel(self.colour_tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setWhatsThis("")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setWordWrap(False)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_25)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.load_params_from_file = QtWidgets.QPushButton(self.colour_tab)
        self.load_params_from_file.setObjectName("load_params_from_file")
        self.gridLayout_13.addWidget(self.load_params_from_file, 0, 0, 1, 1)
        self.plot_parameter = QtWidgets.QPushButton(self.colour_tab)
        self.plot_parameter.setObjectName("plot_parameter")
        self.gridLayout_13.addWidget(self.plot_parameter, 2, 0, 1, 1)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.gridLayout_13)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_26 = QtWidgets.QLabel(self.colour_tab)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.parameter_data_select = QtWidgets.QSpinBox(self.colour_tab)
        self.parameter_data_select.setObjectName("parameter_data_select")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.parameter_data_select)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_27 = QtWidgets.QLabel(self.colour_tab)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_10.addWidget(self.label_27)
        self.param_change_alpha = QtWidgets.QDoubleSpinBox(self.colour_tab)
        self.param_change_alpha.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.param_change_alpha.setDecimals(4)
        self.param_change_alpha.setMaximum(1.0)
        self.param_change_alpha.setSingleStep(0.001)
        self.param_change_alpha.setObjectName("param_change_alpha")
        self.horizontalLayout_10.addWidget(self.param_change_alpha)
        self.label_31 = QtWidgets.QLabel(self.colour_tab)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_10.addWidget(self.label_31)
        self.param_change_R = QtWidgets.QDoubleSpinBox(self.colour_tab)
        self.param_change_R.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.param_change_R.setDecimals(4)
        self.param_change_R.setSingleStep(0.001)
        self.param_change_R.setObjectName("param_change_R")
        self.horizontalLayout_10.addWidget(self.param_change_R)
        self.label_28 = QtWidgets.QLabel(self.colour_tab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_10.addWidget(self.label_28)
        self.param_change_dB = QtWidgets.QDoubleSpinBox(self.colour_tab)
        self.param_change_dB.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.param_change_dB.setDecimals(4)
        self.param_change_dB.setSingleStep(0.0001)
        self.param_change_dB.setObjectName("param_change_dB")
        self.horizontalLayout_10.addWidget(self.param_change_dB)
        self.label_33 = QtWidgets.QLabel(self.colour_tab)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_10.addWidget(self.label_33)
        self.param_change_A = QtWidgets.QDoubleSpinBox(self.colour_tab)
        self.param_change_A.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.param_change_A.setDecimals(4)
        self.param_change_A.setMaximum(10000.0)
        self.param_change_A.setSingleStep(0.5)
        self.param_change_A.setObjectName("param_change_A")
        self.horizontalLayout_10.addWidget(self.param_change_A)
        self.label_34 = QtWidgets.QLabel(self.colour_tab)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_10.addWidget(self.label_34)
        self.param_change_slope = QtWidgets.QDoubleSpinBox(self.colour_tab)
        self.param_change_slope.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.param_change_slope.setDecimals(4)
        self.param_change_slope.setMinimum(-50.0)
        self.param_change_slope.setMaximum(50.0)
        self.param_change_slope.setSingleStep(0.25)
        self.param_change_slope.setObjectName("param_change_slope")
        self.horizontalLayout_10.addWidget(self.param_change_slope)
        self.label_29 = QtWidgets.QLabel(self.colour_tab)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_10.addWidget(self.label_29)
        self.param_change_offset = QtWidgets.QDoubleSpinBox(self.colour_tab)
        self.param_change_offset.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.param_change_offset.setDecimals(4)
        self.param_change_offset.setMinimum(-50.0)
        self.param_change_offset.setMaximum(50.0)
        self.param_change_offset.setSingleStep(0.25)
        self.param_change_offset.setObjectName("param_change_offset")
        self.horizontalLayout_10.addWidget(self.param_change_offset)
        self.formLayout_2.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.parameter_plot_widget = PlotWidget(self.colour_tab)
        self.parameter_plot_widget.setMinimumSize(QtCore.QSize(0, 500))
        self.parameter_plot_widget.setObjectName("parameter_plot_widget")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.parameter_plot_widget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_2.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.checkBox_change_values = QtWidgets.QCheckBox(self.colour_tab)
        self.checkBox_change_values.setObjectName("checkBox_change_values")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.checkBox_change_values)
        self.gridLayout_15.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.colour_tab, "")
        self.para_tab = QtWidgets.QWidget()
        self.para_tab.setObjectName("para_tab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.para_tab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_6 = QtWidgets.QLabel(self.para_tab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.para_tab, "")
        self.anifit_tab = QtWidgets.QWidget()
        self.anifit_tab.setObjectName("anifit_tab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.anifit_tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label = QtWidgets.QLabel(self.anifit_tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_17.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_17.addLayout(self.gridLayout_10, 1, 1, 1, 1)
        self.tabWidget.addTab(self.anifit_tab, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menufile.addAction(self.actionOpen)
        self.menufile.addAction(self.actionSave)
        self.menufile.addAction(self.actionExit)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_Fit_num.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python FMR Fit"))
        self.label_2.setText(_translate("MainWindow", "Select fitting model"))
        self.Button_dropped_points.setText(_translate("MainWindow", "Add to dropped points"))
        self.label_20.setText(_translate("MainWindow", "Amount of functions"))
        self.label_4.setText(_translate("MainWindow", "Select dataset"))
        self.comboBox_Fit_num.setItemText(0, _translate("MainWindow", "---------------------"))
        self.comboBox_Fit_num.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_Fit_num.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_Fit_num.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_fit_model.setItemText(0, _translate("MainWindow", "--------------------------"))
        self.comboBox_fit_model.setItemText(1, _translate("MainWindow", "Gaussian deriv."))
        self.comboBox_fit_model.setItemText(2, _translate("MainWindow", "Lorentz deriv."))
        self.comboBox_fit_model.setItemText(3, _translate("MainWindow", "Dyson deriv."))
        self.comboBox_fit_model.setItemText(4, _translate("MainWindow", "Custom"))
        self.label_23.setText(_translate("MainWindow", "Dropped Points:"))
        self.constraints.setText(_translate("MainWindow", "Set the constraints"))
        self.init_alphatext_2.setText(_translate("MainWindow", "<html><head/><body><p>α (only for Dyson) :</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "From"))
        self.label_8.setText(_translate("MainWindow", "to"))
        self.init_Rtext_2.setText(_translate("MainWindow", "R (resonance field) :"))
        self.label_10.setText(_translate("MainWindow", "From"))
        self.label_11.setText(_translate("MainWindow", "to"))
        self.init_dBtext_2.setText(_translate("MainWindow", "dB (linewidth) :"))
        self.label_12.setText(_translate("MainWindow", "From"))
        self.label_13.setText(_translate("MainWindow", "to"))
        self.init_Atext_2.setText(_translate("MainWindow", "A (amplitude) :"))
        self.label_14.setText(_translate("MainWindow", "From"))
        self.label_15.setText(_translate("MainWindow", "to"))
        self.init_Rtext_3.setText(_translate("MainWindow", "Slope :"))
        self.label_16.setText(_translate("MainWindow", "From"))
        self.label_17.setText(_translate("MainWindow", "to"))
        self.init_Rtext_4.setText(_translate("MainWindow", "Offset :"))
        self.label_18.setText(_translate("MainWindow", "From"))
        self.label_19.setText(_translate("MainWindow", "to"))
        self.label_3.setText(_translate("MainWindow", "Inital parameters for fitting"))
        self.init_offsettext.setText(_translate("MainWindow", "Offset :"))
        self.init_Atext.setText(_translate("MainWindow", "A (amplitude) :"))
        self.init_Slopetext.setText(_translate("MainWindow", "Slope :"))
        self.init_alphatext.setText(_translate("MainWindow", "<html><head/><body><p>α (only for Dyson) :</p></body></html>"))
        self.init_dBtext.setText(_translate("MainWindow", "dB (linewidth) :"))
        self.init_Rtext.setText(_translate("MainWindow", "R (resonance field) :"))
        self.Button_Plot.setText(_translate("MainWindow", "Plot"))
        self.Button_set_fit_params.setText(_translate("MainWindow", "Set initial parameters to fit parameters"))
        self.Button_dyn_fit.setText(_translate("MainWindow", "Dynamic Fit"))
        self.checkBox_dynPlot.setText(_translate("MainWindow", "With dynamic plotting ? (Much Slower !)"))
        self.min_drop_value.setText(_translate("MainWindow", "0"))
        self.Drop_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fit_tab), _translate("MainWindow", "Fit"))
        self.label_24.setText(_translate("MainWindow", "Contour Colour Plot"))
        self.label_5.setText(_translate("MainWindow", "Not fully  implementet"))
        self.colour_button.setText(_translate("MainWindow", "Plot in 2D colour"))
        self.label_21.setText(_translate("MainWindow", "Colour ticks (Integer)"))
        self.colour_tick_edit.setText(_translate("MainWindow", "256"))
        self.label_22.setText(_translate("MainWindow", "Colour Map (String)"))
        self.colour_map_edit.setText(_translate("MainWindow", "inferno"))
        self.label_25.setText(_translate("MainWindow", "Parameters"))
        self.load_params_from_file.setText(_translate("MainWindow", "Load parameters from file"))
        self.plot_parameter.setText(_translate("MainWindow", "Plot parameter"))
        self.label_26.setText(_translate("MainWindow", "Select the angle:"))
        self.label_27.setText(_translate("MainWindow", "α (only for Dyson) :"))
        self.label_31.setText(_translate("MainWindow", "R (resonance field) :"))
        self.label_28.setText(_translate("MainWindow", "dB (linewidth) :"))
        self.label_33.setText(_translate("MainWindow", "A (amplitude) :"))
        self.label_34.setText(_translate("MainWindow", "Slope :"))
        self.label_29.setText(_translate("MainWindow", "Offset :"))
        self.checkBox_change_values.setText(_translate("MainWindow", "Change values"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colour_tab), _translate("MainWindow", "Colour-Plotting"))
        self.label_6.setText(_translate("MainWindow", "Not yet implementet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.para_tab), _translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Not yet implementet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.anifit_tab), _translate("MainWindow", "Anisotropy Constant Fit"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
from pyqtgraph import PlotWidget
