# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        print('Test')
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_load_sec_meas = QtWidgets.QPushButton(Form)
        self.button_load_sec_meas.setObjectName("button_load_sec_meas")
        self.verticalLayout_2.addWidget(self.button_load_sec_meas)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_freq_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_freq_1.setObjectName("lineEdit_freq_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_freq_1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_freq_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_freq_2.setObjectName("lineEdit_freq_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_freq_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.button_calc = QtWidgets.QPushButton(Form)
        self.button_calc.setObjectName("button_calc")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.button_calc)
        self.spinbox_offset = QtWidgets.QSpinBox(Form)
        self.spinbox_offset.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinbox_offset.setMaximum(360)
        self.spinbox_offset.setObjectName("spinbox_offset")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinbox_offset)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.button_save = QtWidgets.QPushButton(Form)
        self.button_save.setObjectName("button_save")
        self.verticalLayout_2.addWidget(self.button_save)
        self.combined_plot = Small_Plot(Form)
        self.combined_plot.setObjectName("combined_plot")
        self.verticalLayout_2.addWidget(self.combined_plot)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_load_sec_meas.setText(_translate("Form", "Load second measurement"))
        self.label_4.setText(_translate("Form", "Frequencies"))
        self.label.setText(_translate("Form", "Measurment 1:"))
        self.lineEdit_freq_1.setText(_translate("Form", "9.8"))
        self.label_2.setText(_translate("Form", "Measurment 2:"))
        self.lineEdit_freq_2.setText(_translate("Form", "9.4"))
        self.label_3.setText(_translate("Form", "Offset"))
        self.button_calc.setText(_translate("Form", "Calculate"))
        self.button_save.setText(_translate("Form", "Save combination"))
from CustomWidgets import Small_Plot
